project:
  type: website
  output-dir: docs

website:
  title: "wesley_blog"
  navbar:
    right:
      - icon: github
        href: https://github.com/Wesleyhuang123
    left: 
      - about.qmd
      - Tasks.qmd
format:
  html:
    theme: minty
    css: styles.css

editor: visual

